title: DiG Computers
description: Building the Future of Computing
header_pages:
  - index.md
style: light # dark (default), light or hacker
footer: '<a href="https://mailchi.mp/14c1b67a4822/sign-up">
sign up</a> to get the latest updates'
remote_theme: "b2a3e8/jekyll-theme-console"
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins